### ISSUE TITLE
Use github releases and publish .aar file in them

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android-nativesdk#10]
Add the .aar file used in the build of nunchuk android app in github releases of this repo: (the built aar generated from building this repo that used for upstream apk on github apk and google play)

https://github.com/nunchuk-io/nunchuk-android-nativesdk/releases

This also can be done instead in: https://github.com/nunchuk-io/nunchuk-android/releases/ (Add asset for .aar file)

Thus will enable easier building of the app (no need to compile this repo to generate aar as there a precompiled file to download) and also helpful for reproducible-builds verification  (there is a file to compare against and to use for building android app to find rb issues not related to this repo), publishing the commit which used to build the file used in the version (or using matched tag) is also needed, related issue is #8 to tag releases in this repo for that purpose.

**Comment by JayceLuong** [comment]
Use Jitpack to publish our sdk, check it [here](https://github.com/nunchuk-io/nunchuk-android-nativesdk-prebuild)
