### ISSUE TITLE
Make .install_linux_deps.sh sh compatible or add bash shebang to it

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android-nativesdk#3]
Running `sh .install_linux_deps.sh` on debian will fail with error `pushd: not found` as `pushd` and `popd` used a lot in this script which require shell like bash in order to work, so either change the code to use another mechanism to change directories or add `#!/bin/bash` to top of the file to make it run by bash and require it in order to run.

**Comment by JayceLuong** [comment]
Added bash to top of `install_linux_deps.sh`

**Comment by emanuelb** [comment]
Issue is fixed in https://github.com/nunchuk-io/nunchuk-android-nativesdk/commit/36af375f6f60728d871f5c0df63391395b1289cf
