### ISSUE TITLE
Add ndkVersion with static value to build.gradle for newer&reproducible NDK usage and use newer supported version

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android-nativesdk#4]
Ndk version used is old 21 (r21e from January 2021) and not specified in build.gradle via ndkVersion option.

Currently the latest stable release is: 25.1.8937393 (r25b) https://developer.android.com/ndk/downloads

The readme mention using version 21.0.6113669 

https://github.com/nunchuk-io/nunchuk-android-nativesdk/blob/e37f80fb75b81b9bf0794f0c579989a11a1f3352/README.md#L10
https://github.com/nunchuk-io/nunchuk-android-nativesdk/blob/e37f80fb75b81b9bf0794f0c579989a11a1f3352/README.md#L63

While running gradle command such as `./gradlew clean` or ` ./gradlew help` in repo (in case ndk is not installed) will install different ndk version 21.4.7075529 as can be seen from output:
```
Checking the license for package NDK (Side by side) 21.4.7075529 in /home/appuser/app/sdk/licenses
License for package NDK (Side by side) 21.4.7075529 accepted.
Preparing "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)".
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" ready.
Installing NDK (Side by side) 21.4.7075529 in /home/appuser/app/sdk/ndk/21.4.7075529
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" complete.
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" finished.
```
and is happening in Containerfile I wrote at: https://github.com/nunchuk-io/nunchuk-android-nativesdk/issues/1#issuecomment-1368618670

it's better to declare the version of the ndk with ndkVersion property in build.gradle, thus helping to reproducible builds as the build will ask for the specified ndk version instead of using whats installed on the machine or will be installed as part of gradle commands.

see "Configure specific versions of the NDK in your project" for more details: https://developer.android.com/studio/projects/install-ndk#apply-specific-version

Also `android.useDeprecatedNdk=true` is used in `gradle.properties` and should be removed.
https://github.com/nunchuk-io/nunchuk-android-nativesdk/blob/195f9916bef0e67c5dcc881df00365d16454c51f/gradle.properties#L4

Fix:

1. Remove the `android.useDeprecatedNdk=true` from gradle.properties, see related issue with more warnings during compilation: #2
2. Upgrade instructions to use supported ndk version: 25.1.8937393
3. Add `ndkVersion` to build.gradle file that specify which ndk version will be used.

**Comment by JayceLuong** [comment]
Added `ndkVersion "21.4.7075529"` to `build.gradle`

**Comment by emanuelb** [comment]
This issue is partially fixed as only setting of ndkVersion property and removing of useDeprecatedNdk were done:
https://github.com/nunchuk-io/nunchuk-android-nativesdk/commit/27eed1896373e0a6b207c66f6d9eb2803561dd2f

The last part is updating the ndkVersion to newer supported version such as `25.1.8937393`

**Comment by emanuelb** [comment]
This issue can remain closed, I opened new issue regarding updating ndkVersion at: #7
