### ISSUE TITLE
publish command fail after invoking task assembleArm64_v8aDebug per instructions in documentation on latest version (works if using assembleArm64_v8aRelease instead)

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android-nativesdk#5]
on latest version commit https://github.com/nunchuk-io/nunchuk-android-nativesdk/commit/0131fcddacae4b448893040e26f70d126d0c0554
Running the commands from documentation in README.md file:

https://github.com/nunchuk-io/nunchuk-android-nativesdk/blob/e37f80fb75b81b9bf0794f0c579989a11a1f3352/README.md#L66-L69

will fail with error in command `./gradlew publish`

```
> Task :publishMavenPublicationToMavenLocalRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenPublicationToMavenLocalRepository'.
> Failed to publish publication 'maven' to repository 'MavenLocal'
   > Invalid publication 'maven': artifact file does not exist: '/home/appuser/app/nunchuk/nunchuk-android-nativesdk/build/outputs/aar/nunchuk-android-nativesdk-arm64_v8a-release.aar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Running task `assembleArm64_v8aRelease` instead of `assembleArm64_v8aDebug` will work.

In previous version like the one before latest source code release in this repo the instructions were valid and the task `assembleArm64_v8aDebug` worked as used in Containerfile at: https://github.com/nunchuk-io/nunchuk-android-nativesdk/issues/1#issuecomment-1368618670

**Comment by JayceLuong** [comment]
We change to build `assembleArm64_v8aRelease` instead. I will update the build instruction
