### ISSUE TITLE
Use newer supported ndkVersion

### ISSUE THREAD

**Issue by emanuelb** [nunchuk-io/nunchuk-android-nativesdk#7]
Ndk version used is old and not supported anymore (r21e from January 2021)
https://github.com/nunchuk-io/nunchuk-android-nativesdk/blob/27eed1896373e0a6b207c66f6d9eb2803561dd2f/build.gradle#L9

Currently the latest stable release is: 25.1.8937393 (r25b) https://developer.android.com/ndk/downloads
History of changes in recent ndk versions: https://developer.android.com/ndk/downloads/revision_history

Use a newer supported ndk version instead, it also might be required to fix #6 in case newer clang version is needed to fix it.

**Comment by JayceLuong** [comment]
Updated support latest ndkVersion 25.1.8937393
